services:
  - type: web
    name: your-app
    env: python
    buildCommand: |
      curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      sudo apt-get install git-lfs
      git lfs install
      git lfs pull
      pip install -r requirements.txt
    startCommand: gunicorn app:app