FROM python:3.10

# Install Git LFS
RUN apt-get update && \
    apt-get install -y curl && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get install -y git-lfs

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy application code
COPY . /app
WORKDIR /app

# Install LFS files
RUN git lfs install && git lfs pull

# Command to run the application
CMD ["gunicorn", "app:app"]

